site_name: McGill CS RESTify Experiment
site_url: https://www.cs.mcgill.ca/~mschie3/restify
nav:
    - Welcome: index.md
    - Preliminaries: preliminaries.md
    - Task Material: material.md
    - Upload: upload.md
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: mcgill
    accent: red
extra_css:
    - stylesheets/extra.css

